# Generated by Django 3.0.2 on 2020-01-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_ip_without_dots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ip_without_dots',
            new_name='ip_with_bars',
        ),
    ]
