# Generated by Django 3.0.2 on 2020-01-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200109_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ip_without_dots',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
